# Generated by Django 3.0.1 on 2019-12-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Specifications', 'verbose_name_plural': 'Specifications'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='This can be null', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_app.Category'),
        ),
    ]
