# Generated by Django 3.0.1 on 2019-12-23 11:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_auto_20191223_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
